### ISSUE TITLE
Error executing nodejs(0.12.4) with koa

### ISSUE THREAD

**Issue by rohitgup14** [rethinkdb/rethinkdb-example-nodejs#16]
$ node --harmony app.js
/<location>/rethinkdb-example-nodejs/todo-angular-koa/node_modules/rethinkdb/ast.js:127
    if (!options.noreply && typeof callback !== 'function') {
                ^
TypeError: Cannot read property 'noreply' of undefined
    at IndexWait.TermBase.run (/<location>/rethinkdb-example-nodejs/todo-angular-koa/node_modules/rethinkdb/ast.js:127:17)
    at /<location>/rethinkdb-example-nodejs/todo-angular-koa/app.js:128:45
    at TcpConnection.<anonymous> (/<location>/rethinkdb-example-nodejs/todo-angular-koa/node_modules/rethinkdb/net.js:78:16)
    at TcpConnection.g (events.js:199:16)
    at TcpConnection.emit (events.js:104:17)
    at Socket.handshake_callback (/<location>/rethinkdb-example-nodejs/todo-angular-koa/node_modules/rethinkdb/net.js:459:23)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by danielmewes** [comment]
Thanks for the report @rohitgup14. That's weird. @deontologician any ideas?

**Comment by deontologician** [comment]
This tutorial is pretty out of date, it has a RethinkDB 1.12 driver dependency. It's possible more recent versions have fixed this bug. It seems not to be checking if options is null, which would come up all the time.

**Comment by samkelleher** [comment]
Same error here running on node v4. The _todo-angular-express-promise_ app gives this error `Cannot read property 'noreply' of undefined` on startup and is using version 2.0 of the driver, while the _todo-angular-express_ works without problems - which interestingly is using a much older driver version (1.12.0).

**Comment by danielmewes** [comment]
Thanks for letting us know @samkelleher.
Once you get things running with the latest driver, a pull request would be amazing so we can merge it into the example code :-)

@deontologician About the original issue: Do you think we could just bump the angular/koa example to using the latest driver?

**Comment by deontologician** [comment]
I've bumped it and made it unbounded (not advised in general, but this is for a tutorial). I think longterm we should integrate these tutorials into our test-suite for new releases or deprecate them

**Comment by danielmewes** [comment]
@deontologician Fair enough. Did you check that the code actually works with the new driver (in case we changed the syntax or name of some command)?

**Comment by deontologician** [comment]
Nope, I just bumped it up. @samkelleher's comment suggests that it doesn't atually work, but since it didn't work anyway, the situation isn't really worse...
