### ISSUE TITLE
how to start retinkdb

### ISSUE THREAD

**Issue by lh8725473** [rethinkdb/rethinkdb-example-nodejs#21]
$ node app.js
{ ReqlDriverError: Could not connect to localhost:28015.
connect ECONNREFUSED 127.0.0.1:28015
    at ReqlDriverError.ReqlError [as constructor](D:mygitgubrethinkdb-example
-nodejsrethinkdb-example-nodejs-mastertodo-angular-expressnode_modulesrethin
kdberrors.js:23:13)
    at new ReqlDriverError (D:\mygitgub\rethinkdb-example-nodejs\rethinkdb-examp
le-nodejs-master\todo-angular-express\node_modules\rethinkdb\errors.js:68:50)
    at TcpConnection.<anonymous> (D:\mygitgub\rethinkdb-example-nodejs\rethinkdb
-example-nodejs-master\todo-angular-express\node_modules\rethinkdb\net.js:94:27)

```
at TcpConnection.g (events.js:291:16)
at emitOne (events.js:96:13)
at TcpConnection.emit (events.js:188:7)
at Socket.<anonymous> (D:\mygitgub\rethinkdb-example-nodejs\rethinkdb-exampl
```

e-nodejs-master\todo-angular-express\node_modules\rethinkdb\net.js:705:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'ReqlDriverError',
  msg: 'Could not connect to localhost:28015.\nconnect ECONNREFUSED 127.0.0.1:28
015',
  frames: undefined,
  message: 'Could not connect to localhost:28015.\nconnect ECONNREFUSED 127.0.0.
1:28015' }

**Comment by jeffreysbrother** [comment]
First fun the command `rethinkdb`. Then, in another terminal tab, start the server with `node app.js`.

**Comment by tokiodeo** [comment]
1. Make sure port 28015 is active and open for connection.

2. must pass a configuration object for example:

 `const = config_rethinkdb = {
    "host": "",
    "port": ,
    "db": "",
    "user": "",
    "password": ""
  }`

 `r.connect(config_rethinkdb)`
